apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-depl
  namespace: tasks-system
spec:
  replicas: 1
  startegy:
    type: Recreate
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: tasks
          image: tasks:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m" # half of a core: "50ms/100ms" , single threaded.
          ports:
            - containerPort: 8000
              name: tasks-api
          env:
            - name: TASKS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: tasks-config
                  key: db_user
                  optional: true

            - name: TASKS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: tasks-config
                  key: db_password
                  optional: true

            - name: TASKS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: tasks-config
                  key: db_host
                  optional: true
            - name: TASKS_DB_DIABLE_TLS
              valueFrom:
                configMapKeyRef:
                  name: tasks-config
                  key: db_disabletls

            - name: TASKS_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: tasks-config
                  key: redis_host

            - name: TASKS_REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: tasks-config
                  key: redis_password

            - name: TASKS_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: tasks-config
                  key: rabbit_host

            - name: TASKS_RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: tasks-config
                  key: rabbit_user

            - name: TASKS_RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: tasks-config
                  key: rabbit_password

            - name: TASKS_RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: tasks-config
                  key: rabbit_password
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu #reads limits and rounds it up and gives the app that many threads.
            - name: GOGC
              value: "off"
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-svc
  namespace: tasks-system
spec:
  type: ClusterIP
  selector:
    app: tasks
  ports:
    - port: 8000
      targetPort: tasks-api
      name: tasks-api
